### ISSUE TITLE
Alternative to Drone wave

### ISSUE THREAD

**Issue by ChronosWS** [tiwaz1994/DynamicBulwarks#17]
In playtests with my group, we have found the drone wave to be highly frustrating - shooting a dozen or more tiny drones while they progressively destroy everything is highly annoying.  An alternative that maintains the air threat without being frustrating would be nice.  Consider:
1. Fewer drones at a time
2. Allow drones to start spawning during normal waves in smaller numbers
3. Alternative ways to destroy drones (alternative AA?)

**Comment by tiwaz1994** [comment]
I  think the drone wave itself is fine, we just need to scale it according to wave count. Also if all infantry is dead and there are just drones left, wave should end.

**Comment by ChronosWS** [comment]
FIxed by 269343fb63f64f2368faa4c05fc584d3417aa7eb
